name: steelcraft-staging-lane-00-uiux
services:
- name: steelcraft-portal-preview
  github:
    repo: NeroaEngine/steelcraft
    branch: staging-lane-00-uiux
    deploy_on_push: true
  environment_slug: node-js
  build_command: npm run build
  run_command: node server.js
  routes:
  - path: /
