import type { CanvasCardManifest } from './card-manifest-contract';

export const estimatingCardManifests: CanvasCardManifest[] = [
  {
    id: 'manufacturer-import',
    title: 'Manufacturer Import',
    roomId: 'estimating',
    description: 'Imports and reviews manufacturer quote information before it enters the estimate.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'quote'],
    fields: [
      { id: 'manufacturer', label: 'Manufacturer', type: 'select', editable: true, required: true, options: ['Whirlwind', 'Nucor', 'Chief', 'Metallic', 'MBS', 'Other'] },
      { id: 'fileName', label: 'File Name', type: 'text', editable: true },
      { id: 'reviewStatus', label: 'Review Status', type: 'computed', editable: false },
      { id: 'manufacturerCost', label: 'Manufacturer Cost', type: 'currency', editable: true },
    ],
    actions: ['upload', 'review', 'mapToEstimate'],
    outputs: ['manufacturerCost', 'buildingRequirements', 'receipt'],
  },
  {
    id: 'estimate',
    title: 'Estimate Worksheet',
    roomId: 'estimating',
    description: 'Template-backed estimate inputs and calculated totals.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'quote'],
    fields: [
      { id: 'buildingCost', label: 'Building Cost', type: 'currency', editable: true, required: true },
      { id: 'localTaxRate', label: 'Local Tax Rate', type: 'percent', editable: true },
      { id: 'markupPercent', label: 'Markup', type: 'percent', editable: true },
      { id: 'freight', label: 'Freight', type: 'currency', editable: true },
      { id: 'engineering', label: 'Engineering', type: 'currency', editable: true },
      { id: 'laborCost', label: 'Labor Cost', type: 'currency', editable: true },
      { id: 'total', label: 'Total', type: 'computed', editable: false },
    ],
    actions: ['calculate', 'saveEstimate', 'sendToProposal'],
    outputs: ['subtotal', 'tax', 'markup', 'total', 'costPerSf', 'receipt'],
  },
  {
    id: 'alternates',
    title: 'Alternates',
    roomId: 'estimating',
    description: 'Structured alternates that can convert into contract value after customer acceptance.',
    size: 'wide',
    priority: 'secondary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'quote'],
    fields: [
      { id: 'description', label: 'Description', type: 'text', editable: true },
      { id: 'cost', label: 'Cost', type: 'currency', editable: true },
      { id: 'feePercent', label: 'Fee %', type: 'percent', editable: true },
      { id: 'taxPercent', label: 'Tax %', type: 'percent', editable: true },
      { id: 'accepted', label: 'Accepted', type: 'checkbox', editable: true },
    ],
    actions: ['addAlternate', 'priceAlternates', 'acceptAlternate'],
    outputs: ['proposalAlternateTotal', 'acceptedAlternateTotal', 'receipt'],
  },
  {
    id: 'pricing-summary',
    title: 'Pricing Summary',
    roomId: 'estimating',
    description: 'Generated quote financial summary for proposal review.',
    size: 'large',
    priority: 'supporting',
    capabilities: ['inspect', 'quote'],
    fields: [
      { id: 'subtotal', label: 'Subtotal', type: 'computed', editable: false },
      { id: 'tax', label: 'Tax', type: 'computed', editable: false },
      { id: 'markup', label: 'Markup', type: 'computed', editable: false },
      { id: 'total', label: 'Proposal Total', type: 'computed', editable: false },
    ],
    actions: ['refreshProjection'],
    outputs: ['proposalTotal', 'summaryProjection'],
  },
  {
    id: 'margin-analysis',
    title: 'Margin Analysis',
    roomId: 'estimating',
    description: 'Generated profitability checkpoint before proposal output.',
    size: 'medium',
    priority: 'supporting',
    capabilities: ['inspect', 'quote'],
    fields: [
      { id: 'contractValue', label: 'Contract Value', type: 'computed', editable: false },
      { id: 'totalCost', label: 'Total Cost', type: 'computed', editable: false },
      { id: 'grossProfit', label: 'Gross Profit', type: 'computed', editable: false },
      { id: 'grossMargin', label: 'Gross Margin', type: 'computed', editable: false },
    ],
    actions: ['refreshProjection'],
    outputs: ['grossProfit', 'grossMargin', 'status'],
  },
];
