import type { CanvasCardManifest } from './card-manifest-contract';
import { estimatingCardManifests } from './estimating-card-manifests';

const salesCardManifests: CanvasCardManifest[] = [
  {
    id: 'lead-generation',
    title: 'Lead Generation',
    roomId: 'crm-sales',
    description: 'Captures lead source, customer, bid due date, estimator, and follow-up state before quote creation.',
    size: 'medium',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'quote'],
    fields: [
      { id: 'leadSource', label: 'Lead Source', type: 'text', editable: true, required: true },
      { id: 'customer', label: 'Customer', type: 'text', editable: true, required: true },
      { id: 'bidDueDate', label: 'Bid Due Date', type: 'date', editable: true },
      { id: 'estimator', label: 'Estimator', type: 'text', editable: true },
      { id: 'status', label: 'Status', type: 'select', editable: true, options: ['Lead', 'Qualified', 'Estimating', 'Proposal Sent', 'Follow Up', 'Negotiation', 'Awarded'] },
    ],
    actions: ['createLead', 'qualifyLead', 'createQuote', 'scheduleFollowUp'],
    outputs: ['leadRecord', 'quoteSeed', 'receipt'],
  },
  {
    id: 'quote',
    title: 'Quote',
    roomId: 'crm-sales',
    description: 'Primary quote record. No SCB project number is issued until award.',
    size: 'medium',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'quote'],
    fields: [
      { id: 'quoteNumber', label: 'Quote Number', type: 'computed', editable: false },
      { id: 'projectName', label: 'Project Name', type: 'text', editable: true, required: true },
      { id: 'customer', label: 'Customer', type: 'text', editable: true, required: true },
      { id: 'quoteType', label: 'Quote Type', type: 'select', editable: true, options: ['Furnish and Erect', 'Erection Only', 'Material Only'] },
    ],
    actions: ['createQuote', 'updateQuote', 'advanceStage'],
    outputs: ['quoteRecord', 'stage', 'receipt'],
  },
  {
    id: 'project-information',
    title: 'Project Information',
    roomId: 'estimating',
    description: 'Customer, billing, estimator, and project metadata from the approved Project Information template.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'quote'],
    fields: [
      { id: 'estimator', label: 'Estimator', type: 'text', editable: true, required: true },
      { id: 'projectName', label: 'Project Name', type: 'text', editable: true, required: true },
      { id: 'projectAddress', label: 'Project Address', type: 'textarea', editable: true },
      { id: 'customerCompany', label: 'Customer Company', type: 'text', editable: true, required: true },
      { id: 'billingEmail', label: 'Billing Email', type: 'text', editable: true },
    ],
    actions: ['saveProjectInfo', 'validateRequiredFields'],
    outputs: ['projectInfoProjection', 'receipt'],
  },
  {
    id: 'working-sheet',
    title: 'Working Sheet',
    roomId: 'estimating',
    description: 'Scope, loads, code, payment terms, project notes, and proposal language inputs.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'quote'],
    fields: [
      { id: 'buildingCode', label: 'Building Code', type: 'text', editable: true },
      { id: 'riskCategory', label: 'Risk Category', type: 'select', editable: true, options: ['I - Low', 'II - Normal', 'III - High', 'IV - Essential'] },
      { id: 'windLoad', label: 'Wind Load', type: 'text', editable: true },
      { id: 'exposure', label: 'Exposure', type: 'select', editable: true, options: ['TBD', 'B', 'C', 'D'] },
      { id: 'projectNotes', label: 'Project Notes', type: 'textarea', editable: true },
    ],
    actions: ['saveWorkingSheet', 'mapScopeToProposal'],
    outputs: ['scopeProjection', 'proposalLanguageSeed', 'receipt'],
  },
];

const metalBuildingBackendCardManifests: CanvasCardManifest[] = [
  {
    id: 'plan-upload',
    title: 'Plan Upload',
    roomId: 'model-designer',
    description: 'Accepts customer plan sets and creates a versioned plan record for recognition and modeling.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'document', 'quote'],
    fields: [
      { id: 'fileName', label: 'File Name', type: 'text', editable: true, required: true },
      { id: 'planType', label: 'Plan Type', type: 'select', editable: true, options: ['PDF', 'DWG', 'DXF', 'Image', 'Other'] },
      { id: 'revision', label: 'Revision', type: 'text', editable: true },
      { id: 'uploadStatus', label: 'Upload Status', type: 'computed', editable: false },
    ],
    actions: ['uploadPlan', 'versionPlan', 'sendToRecognition'],
    outputs: ['planRecord', 'planVersion', 'receipt'],
  },
  {
    id: 'building-designer',
    title: 'Building Designer',
    roomId: 'model-designer',
    description: 'Manual and AI-assisted metal building model assumptions.',
    size: 'full',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff', 'quote'],
    fields: [
      { id: 'width', label: 'Width', type: 'number', editable: true, required: true },
      { id: 'length', label: 'Length', type: 'number', editable: true, required: true },
      { id: 'eaveHeight', label: 'Eave Height', type: 'number', editable: true },
      { id: 'roofPitch', label: 'Roof Pitch', type: 'text', editable: true },
      { id: 'baySpacing', label: 'Bay Spacing', type: 'number', editable: true },
    ],
    actions: ['generateModel', 'updateModel', 'sendToTakeoff'],
    outputs: ['buildingModel', 'modelAssumptions', 'receipt'],
  },
  {
    id: 'structural',
    title: 'Structural',
    roomId: 'model-designer',
    description: 'Frames, columns, girts, purlins, bracing, base angle, and anchor bolt assumptions.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff'],
    fields: [
      { id: 'frameType', label: 'Frame Type', type: 'select', editable: true, options: ['Rigid Frame', 'Lean-To', 'Single Slope', 'Multi-Span', 'TBD'] },
      { id: 'bayCount', label: 'Bay Count', type: 'number', editable: true },
      { id: 'bracingType', label: 'Bracing Type', type: 'text', editable: true },
      { id: 'columnLayout', label: 'Column Layout', type: 'textarea', editable: true },
    ],
    actions: ['updateStructuralModel', 'sendToMbs'],
    outputs: ['structuralTakeoff', 'mbsStructuralPayload', 'receipt'],
  },
  {
    id: 'roof-systems',
    title: 'Roof Systems',
    roomId: 'model-designer',
    description: 'Roof panels, standing seam upgrade, gutters, downspouts, roof curbs, and accessories.',
    size: 'wide',
    priority: 'secondary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff'],
    fields: [
      { id: 'roofType', label: 'Roof Type', type: 'select', editable: true, options: ['Standard Panel', 'Standing Seam', 'TBD'] },
      { id: 'roofColor', label: 'Roof Color', type: 'text', editable: true },
      { id: 'gutters', label: 'Gutters', type: 'checkbox', editable: true },
      { id: 'downspouts', label: 'Downspouts', type: 'checkbox', editable: true },
    ],
    actions: ['updateRoofSystem', 'priceRoofAlternates'],
    outputs: ['roofTakeoff', 'roofAlternates', 'receipt'],
  },
  {
    id: 'wall-systems',
    title: 'Wall Systems',
    roomId: 'model-designer',
    description: 'Wall panels, wainscot, insulation, trim, flashings, and wall color selections.',
    size: 'wide',
    priority: 'secondary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff'],
    fields: [
      { id: 'wallPanelType', label: 'Wall Panel Type', type: 'text', editable: true },
      { id: 'wallColor', label: 'Wall Color', type: 'text', editable: true },
      { id: 'wainscot', label: 'Wainscot', type: 'checkbox', editable: true },
      { id: 'insulation', label: 'Insulation', type: 'checkbox', editable: true },
    ],
    actions: ['updateWallSystem', 'priceWallAlternates'],
    outputs: ['wallTakeoff', 'wallAlternates', 'receipt'],
  },
  {
    id: 'doors',
    title: 'Doors',
    roomId: 'model-designer',
    description: 'Roll-up, sectional, walk, full-vision, and vendor-priced door selections.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff'],
    fields: [
      { id: 'doorType', label: 'Door Type', type: 'select', editable: true, options: ['Roll-Up', 'Sectional', 'Walk Door', 'Full Vision', 'Sliding', 'Other'] },
      { id: 'width', label: 'Width', type: 'number', editable: true },
      { id: 'height', label: 'Height', type: 'number', editable: true },
      { id: 'quantity', label: 'Quantity', type: 'number', editable: true },
      { id: 'vendor', label: 'Vendor', type: 'select', editable: true, options: ['Dynamic Door', 'Other'] },
    ],
    actions: ['addDoor', 'priceDoor', 'mapToDynamicDoor'],
    outputs: ['doorSchedule', 'doorTakeoff', 'receipt'],
  },
  {
    id: 'windows',
    title: 'Windows',
    roomId: 'model-designer',
    description: 'Windows, storefront glass, openings, and trim packages.',
    size: 'medium',
    priority: 'secondary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff'],
    fields: [
      { id: 'windowType', label: 'Window Type', type: 'select', editable: true, options: ['Fixed', 'Operable', 'Storefront', 'Other'] },
      { id: 'width', label: 'Width', type: 'number', editable: true },
      { id: 'height', label: 'Height', type: 'number', editable: true },
      { id: 'quantity', label: 'Quantity', type: 'number', editable: true },
    ],
    actions: ['addWindow', 'priceWindow', 'sendToTakeoff'],
    outputs: ['windowSchedule', 'windowTakeoff', 'receipt'],
  },
  {
    id: 'accessories',
    title: 'Accessories',
    roomId: 'model-designer',
    description: 'Louvers, vents, canopies, roof curbs, exhaust fans, mezzanines, and other accessories.',
    size: 'wide',
    priority: 'secondary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff'],
    fields: [
      { id: 'accessoryType', label: 'Accessory Type', type: 'select', editable: true, options: ['Louver', 'Vent', 'Canopy', 'Roof Curb', 'Exhaust Fan', 'Mezzanine', 'Other'] },
      { id: 'quantity', label: 'Quantity', type: 'number', editable: true },
      { id: 'notes', label: 'Notes', type: 'textarea', editable: true },
    ],
    actions: ['addAccessory', 'priceAccessory', 'sendToTakeoff'],
    outputs: ['accessorySchedule', 'accessoryTakeoff', 'receipt'],
  },
  {
    id: 'component-takeoff',
    title: 'Component Takeoff',
    roomId: 'model-designer',
    description: 'Generated component takeoff from plan recognition and model selections.',
    size: 'full',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff', 'quote'],
    fields: [
      { id: 'component', label: 'Component', type: 'computed', editable: false },
      { id: 'quantity', label: 'Quantity', type: 'computed', editable: false },
      { id: 'estimateBucket', label: 'Estimate Bucket', type: 'computed', editable: false },
    ],
    actions: ['generateTakeoff', 'reviewTakeoff', 'sendToEstimate'],
    outputs: ['componentTakeoff', 'estimatePayload', 'receipt'],
  },
  {
    id: 'mbs-export',
    title: 'MBS Export',
    roomId: 'model-designer',
    description: 'Builds the Metal Building Software export payload from model, load, and component data.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'takeoff', 'quote'],
    fields: [
      { id: 'projectType', label: 'Project Type', type: 'select', editable: true, options: ['mini-storage', 'metal-building', 'hybrid'] },
      { id: 'exportStatus', label: 'Export Status', type: 'computed', editable: false },
      { id: 'mbsJobNumber', label: 'MBS Job Number', type: 'text', editable: true },
    ],
    actions: ['buildMbsPayload', 'exportToMbs', 'importMbsResults'],
    outputs: ['mbsPayload', 'mbsResult', 'receipt'],
  },
];

const proposalCardManifests: CanvasCardManifest[] = [
  {
    id: 'fe-quotation',
    title: 'F&E Quotation',
    roomId: 'proposal',
    description: 'Generates the furnishing and erection customer-facing quotation from approved estimate data.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'document', 'quote'],
    fields: [
      { id: 'proposalDate', label: 'Proposal Date', type: 'date', editable: true },
      { id: 'scopeSummary', label: 'Scope Summary', type: 'textarea', editable: true },
      { id: 'proposalTotal', label: 'Proposal Total', type: 'computed', editable: false },
    ],
    actions: ['generateFeQuotation', 'reviewProposal', 'sendToCustomer'],
    outputs: ['feQuotationDocument', 'customerProposal', 'receipt'],
  },
  {
    id: 'eo-quotation',
    title: 'EO Quotation',
    roomId: 'proposal',
    description: 'Generates erection-only quotation language and pricing when erection is scoped separately.',
    size: 'wide',
    priority: 'secondary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'document', 'quote'],
    fields: [
      { id: 'erectionScope', label: 'Erection Scope', type: 'textarea', editable: true },
      { id: 'erectionPrice', label: 'Erection Price', type: 'currency', editable: true },
      { id: 'exclusions', label: 'Exclusions', type: 'textarea', editable: true },
    ],
    actions: ['generateEoQuotation', 'reviewProposal', 'sendToCustomer'],
    outputs: ['eoQuotationDocument', 'receipt'],
  },
  {
    id: 'proposal-review',
    title: 'Proposal Review',
    roomId: 'proposal',
    description: 'Final review checkpoint before proposal package is sent.',
    size: 'large',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'document', 'quote'],
    fields: [
      { id: 'estimateApproved', label: 'Estimate Approved', type: 'checkbox', editable: true, required: true },
      { id: 'scopeApproved', label: 'Scope Approved', type: 'checkbox', editable: true, required: true },
      { id: 'proposalNotes', label: 'Proposal Notes', type: 'textarea', editable: true },
    ],
    actions: ['approveProposal', 'requestRevision', 'sendProposal'],
    outputs: ['proposalApproval', 'sentStatus', 'receipt'],
  },
  {
    id: 'proposal-output',
    title: 'Proposal Output',
    roomId: 'proposal',
    description: 'Generated proposal package, PDF output, email handoff, and customer portal update.',
    size: 'large',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'document', 'quote'],
    fields: [
      { id: 'pdfStatus', label: 'PDF Status', type: 'computed', editable: false },
      { id: 'emailStatus', label: 'Email Status', type: 'computed', editable: false },
      { id: 'portalStatus', label: 'Portal Status', type: 'computed', editable: false },
    ],
    actions: ['generatePdf', 'emailProposal', 'publishToPortal'],
    outputs: ['proposalPdf', 'emailRecord', 'portalRecord', 'receipt'],
  },
];

const projectExecutionCardManifests: CanvasCardManifest[] = [
  {
    id: 'contract-conversion',
    title: 'Contract Conversion',
    roomId: 'contract',
    description: 'Converts an awarded quote into an SCB project record only after contract or PO approval.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'project', 'quote'],
    fields: [
      { id: 'contractSigned', label: 'Contract Signed', type: 'checkbox', editable: true, required: true },
      { id: 'depositReceived', label: 'Deposit Received', type: 'checkbox', editable: true, required: true },
      { id: 'pmAssigned', label: 'PM Assigned', type: 'text', editable: true, required: true },
      { id: 'scbProjectNumber', label: 'SCB Project Number', type: 'computed', editable: false },
    ],
    actions: ['validateAward', 'generateScbProject', 'lockQuote'],
    outputs: ['projectRecord', 'scbProjectNumber', 'receipt'],
  },
  {
    id: 'project-delivery',
    title: 'Project Delivery',
    roomId: 'project-delivery',
    description: 'Production hold, approval drawings, revision cycle, release for production, fabrication, and delivery.',
    size: 'full',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'project', 'document'],
    fields: [
      { id: 'engineeringStatus', label: 'Engineering Status', type: 'select', editable: true, options: ['Not Started', 'In Progress', 'Customer Review', 'Revisions', 'Signed and Sealed', 'Released'] },
      { id: 'deliveryDate', label: 'Delivery Date', type: 'date', editable: true },
      { id: 'productionStatus', label: 'Production Status', type: 'text', editable: true },
    ],
    actions: ['updateDeliveryStage', 'releaseForProduction', 'logMilestone'],
    outputs: ['deliveryProjection', 'timelineEvent', 'receipt'],
  },
  {
    id: 'schedule-of-values',
    title: 'Schedule of Values',
    roomId: 'schedule-of-values',
    description: 'Generated SOV from contract value, accepted alternates, and approved change orders.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'billing', 'project'],
    fields: [
      { id: 'contractValue', label: 'Contract Value', type: 'currency', editable: false },
      { id: 'retainage', label: 'Retainage', type: 'percent', editable: true },
      { id: 'currentDraw', label: 'Current Draw', type: 'select', editable: true, options: ['Material 1', 'Material 2', 'Material 3', 'Material 4', 'Labor 1', 'Labor 2'] },
    ],
    actions: ['generateSov', 'approveDraw', 'sendToInvoice'],
    outputs: ['sovDocument', 'drawSchedule', 'receipt'],
  },
  {
    id: 'change-orders',
    title: 'Change Orders',
    roomId: 'change-orders',
    description: 'Creates and approves project change orders and updates contract value and SOV automatically.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'billing', 'project', 'document'],
    fields: [
      { id: 'changeOrderType', label: 'Type', type: 'select', editable: true, options: ['Design Revision', 'Material Escalation', 'Scope Addition', 'Scope Deletion', 'Site Condition', 'Owner Request'] },
      { id: 'description', label: 'Description', type: 'textarea', editable: true, required: true },
      { id: 'amount', label: 'Amount', type: 'currency', editable: true },
      { id: 'approved', label: 'Approved', type: 'checkbox', editable: true },
    ],
    actions: ['createChangeOrder', 'approveChangeOrder', 'updateContractValue'],
    outputs: ['changeOrderDocument', 'updatedContractValue', 'updatedSov', 'receipt'],
  },
  {
    id: 'invoice',
    title: 'Invoice',
    roomId: 'billing-insurance',
    description: 'Generates invoice output from approved SOV draw and updates AR/customer portal.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'billing', 'document'],
    fields: [
      { id: 'drawType', label: 'Draw Type', type: 'select', editable: true, options: ['Material 1', 'Material 2', 'Material 3', 'Material 4', 'Labor 1', 'Labor 2', 'Change Order'] },
      { id: 'invoiceAmount', label: 'Invoice Amount', type: 'computed', editable: false },
      { id: 'dueDate', label: 'Due Date', type: 'date', editable: true },
    ],
    actions: ['generateInvoice', 'sendInvoice', 'createArRecord'],
    outputs: ['invoiceDocument', 'arRecord', 'customerPortalUpdate', 'receipt'],
  },
  {
    id: 'erection',
    title: 'Erection',
    roomId: 'erection',
    description: 'Crew assignment, superintendent view, daily logs, photos, percent complete, and pay applications.',
    size: 'wide',
    priority: 'primary',
    capabilities: ['prompt', 'execute', 'receipt', 'inspect', 'project', 'document'],
    fields: [
      { id: 'crew', label: 'Crew', type: 'text', editable: true },
      { id: 'superintendent', label: 'Superintendent', type: 'text', editable: true },
      { id: 'percentComplete', label: 'Percent Complete', type: 'percent', editable: true },
      { id: 'dailyLog', label: 'Daily Log', type: 'textarea', editable: true },
    ],
    actions: ['updateErectionStatus', 'submitDailyLog', 'uploadPhotos'],
    outputs: ['erectionProjection', 'dailyLogRecord', 'receipt'],
  },
];

export const steelCraftAllCardManifests: CanvasCardManifest[] = [
  ...salesCardManifests,
  ...estimatingCardManifests,
  ...metalBuildingBackendCardManifests,
  ...proposalCardManifests,
  ...projectExecutionCardManifests,
];

export function getSteelCraftAllCardManifests(): CanvasCardManifest[] {
  return steelCraftAllCardManifests;
}

export function getCardManifestsByRoom(roomId: string): CanvasCardManifest[] {
  return steelCraftAllCardManifests.filter((card) => card.roomId === roomId);
}
