import React, { useMemo, useRef, useState } from 'react';
import './accountingLayout.css';

const sections = [
  ['today', 'Today', 'Accounting command center'],
  ['ledger', 'General Ledger', 'Chart of accounts, journal entries, trial balance, and posting history'],
  ['billing', 'Billing', 'Customer invoices, progress billing, and approvals'],
  ['insurance', 'Insurance', 'Certificates, expirations, and compliance tracking'],
  ['purchase-orders', 'Purchase Orders', 'Vendor POs, approvals, receiving, and cost coding'],
  ['receivables', 'Accounts Receivable', 'Customer balances, collections, and payment status'],
  ['payables', 'Accounts Payable', 'Vendor bills, approvals, and scheduled payments'],
  ['sov', 'Schedule of Values', 'Project billing schedule, percent complete, and retainage'],
  ['change-orders', 'Change Orders', 'Pending, approved, billed, and rejected changes'],
  ['reports', 'Reports', 'Financial report library and accounting snapshots'],
  ['comptroller', 'Neroa Comptroller', 'AI matching, review, approval, and posting workflow'],
  ['setup', 'Setup', 'Bank feeds, migrations, integrations, and posting preferences']
];
const validSections = new Set(sections.map(([id]) => id));
const billingRows = [['SC-INV-1042', 'North Ridge Builders - progress billing package', 'Draft'], ['SC-INV-1043', 'Summit Industrial - maintenance platform phase 2', 'Ready'], ['SC-INV-1044', 'Acme Steel Supply - material release invoice', 'Review']];
const insuranceRows = [['Keystone Fabrication Group', 'COI expires in 12 days. Hold new work until updated.', 'Needs review'], ['Summit Industrial', 'General liability and workers comp current.', 'Current'], ['North Ridge Builders', 'Additional insured certificate requested.', 'Pending']];
const poRows = [['PO-22018', 'Steel package - Acme Steel Supply - project cost code 4010', 'Approved'], ['PO-22019', 'Galvanized embeds - vendor confirmation needed', 'Pending'], ['PO-22020', 'Paint and coatings - receiving not complete', 'Receiving']];
const arRows = [['North Ridge Builders', '$82,400 open. Progress draw due this week.', 'Due'], ['Summit Industrial', '$31,500 open. Payment promised Friday.', 'Watch'], ['Acme Steel Supply', '$70,300 open. Statement sent.', 'Open']];
const apRows = [['Central Metals', '$28,900 bill awaiting project manager approval.', 'Approve'], ['Rapid Freight', '$6,450 scheduled for payment run.', 'Scheduled'], ['Keystone Fabrication', '$0 held pending insurance paperwork.', 'Hold']];
const sovRows = [['Warehouse expansion', 'Mobilization 100%, steel package 65%, erection 20%.', 'Billable'], ['Industrial platform', 'Engineering complete, fabrication 80%, field install pending.', 'Review'], ['Storage building', 'Deposit posted, materials not released.', 'Hold']];
const changeOrderRows = [['CO-118', 'North Ridge Builders - added lintels and field welding.', 'Pending approval'], ['CO-119', 'Summit Industrial - stair revision and handrail change.', 'Approved'], ['CO-120', 'Acme Steel Supply - expedited delivery request.', 'Price review']];
const ledgerRows = [['1000 Cash - Operating', 'Debit $214,600. Bank feed connected to review workflow.', 'Active'], ['1100 Accounts Receivable', 'Debit $184,200. Customer balances tied to AR aging.', 'Active'], ['1200 Contract Assets / WIP', 'Debit $91,300. Unbilled work tracked from SOV and job cost.', 'Suggested'], ['2000 Accounts Payable', 'Credit $76,800. Vendor bills tied to AP approval.', 'Active'], ['4000 Sales Revenue', 'Credit $311,000. Billing and SOV entries pending close.', 'Active'], ['5000 Cost of Goods Sold', 'Debit $142,700. PO, bills, and project costs routed here.', 'Review']];
const journalRows = [['JE-10021', 'Progress billing accrual - North Ridge Builders', 'Draft'], ['JE-10022', 'Vendor bill coding - Central Metals', 'Review'], ['JE-10023', 'Bank fee and interest posting', 'Ready']];
const aiLedgerRows = [['Business scan', 'AI reads services, customers, vendors, projects, tax setup, payroll, assets, and bank activity.', 'Ready'], ['Recommended chart', 'AI proposes accounts, subaccounts, cost codes, posting rules, and reporting groups.', 'Draft'], ['Review controls', 'Controller approves, edits, locks, or rejects each account before it goes live.', 'Required'], ['Audit proof', 'Every created account stores source evidence, approver, timestamp, and receipt.', 'Proof']];
const reportRows = [['General Ledger Detail', 'Full account transaction history with source, posting, and audit trail.', 'Available'], ['Trial Balance', 'Debits, credits, and balance by account for close review.', 'Available'], ['Balance Sheet', 'Assets, liabilities, and equity by period.', 'Available'], ['Profit and Loss', 'Revenue, cost, expense, and net income by period.', 'Available'], ['Bank Reconciliation Exceptions', 'Unmatched deposits, withdrawals, transfers, and fees.', 'Available'], ['Posting Approval Report', 'Items approved, rejected, edited, exported, or pending.', 'Available']];
const integrationKey = 'steelcraft_accounting_integrations_native_v2';
const providerContextKey = 'steelcraft_business_provider_setup_context';
const providerEventName = 'steelcraft-business-provider-setup';
const providers = [
  { id: 'quickbooks_online', title: 'QuickBooks Online', kind: 'Cloud accounting', setupUrl: '/connect/business/quickbooks_online/setup' },
  { id: 'quickbooks_desktop_enterprise', title: 'QuickBooks Desktop / Enterprise', kind: 'Desktop connector', setupUrl: '/connect/business/quickbooks_desktop_enterprise/setup' },
  { id: 'foundation_software', title: 'Foundation Software', kind: 'Construction accounting ERP', setupUrl: '/connect/business/foundation_software/setup' }
];
const bankAccounts = {
  quickbooks_online: [['Operating Checking', '**** 8142', 'Imported preview'], ['Payroll Checking', '**** 1027', 'Imported preview'], ['Savings Reserve', '**** 4491', 'Imported preview']],
  quickbooks_desktop_enterprise: [['Desktop Operating', '**** 5520', 'Connector preview'], ['Payroll Clearing', '**** 2261', 'Connector preview']],
  foundation_software: [['Foundation Cash Account', '**** 7104', 'Imported preview'], ['Job Cost Clearing', '**** 3200', 'Imported preview']]
};
const migrationAreas = [['Chart of accounts', 'Map accounts and posting rules', 'Ready to approve'], ['Customers and vendors', 'Import master records', 'Ready to approve'], ['Open invoices', 'Review AR migration', 'Ready to approve'], ['Vendor bills', 'Review AP migration', 'Ready to approve'], ['Bank accounts', 'Review import feed', 'Ready to approve'], ['Job cost and cost codes', 'Map projects and cost codes', 'Ready to approve']];
const defaultProviderState = { status: 'Not connected', authorized: false, connected: false, banks: [], migration: [], approved: [], connectionRef: '', test: 'Not run', lastAction: 'Not started', fireCount: 0 };
function pathSection() { const section = location.pathname.replace(/\/$/, '').match(/^\/portal\/accounting\/?([^/]*)/)?.[1] || 'today'; return validSections.has(section) ? section : 'today'; }
function url(section) { return section === 'today' ? '/portal/accounting' : `/portal/accounting/${section}`; }
function getInitialIntegrationState() { try { return { selected: 'quickbooks_online', message: '', activity: [], providers: {}, ...(JSON.parse(localStorage.getItem(integrationKey)) || {}) }; } catch { return { selected: 'quickbooks_online', message: '', activity: [], providers: {} }; } }
function saveIntegrationState(next) { try { localStorage.setItem(integrationKey, JSON.stringify(next)); } catch {} }
function providerState(state, id) { return { ...defaultProviderState, ...(state.providers[id] || {}) }; }
function providerById(id) { return providers.find((provider) => provider.id === id) || providers[0]; }
function writeProviderContext(provider, status, action) { try { const payload = { provider_id: provider.id, provider_name: provider.title, provider_status: status.status, setup_url: provider.setupUrl, source: `accounting_${action}` }; localStorage.setItem(providerContextKey, JSON.stringify(payload)); window.dispatchEvent(new CustomEvent(providerEventName, { detail: payload })); } catch {} }
function Card({ title, description, children, className = '' }) { return <article className={`feature panel accounting-form-card ${className}`}><h2>{title}</h2>{description && <p>{description}</p>}{children}</article>; }
function Table({ title, rows = [], empty, className = '' }) { return <Card title={title} className={`accounting-full-row accounting-expanded-payables ${className}`}>{rows.length ? <div className="accounting-table">{rows.map((row, index) => <div className="accounting-table-row" key={`${row[0]}-${index}`}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b></div>)}</div> : <div className="accounting-empty">{empty}</div>}</Card>; }
function FireButton({ children, action }) { const fired = useRef(false); const trigger = (event) => { event.preventDefault(); event.stopPropagation(); if (fired.current) return; fired.current = true; action(); window.setTimeout(() => { fired.current = false; }, 240); }; return <button type="button" onPointerDown={trigger} onMouseDown={trigger} onTouchStart={trigger} onClick={trigger}>{children}</button>; }
function Nav({ active, open }) { return <nav className="accounting-section-nav accounting-compact-nav"><div className="accounting-nav-row"><label><span>Room</span><select value={active} onChange={(event) => open(event.target.value)}>{sections.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label><div className="accounting-header-actions compact"><button type="button" onClick={() => open('ledger')}>General Ledger</button><button type="button" onClick={() => open('billing')}>Billing</button><button type="button" onClick={() => open('purchase-orders')}>Purchase Orders</button><button type="button" onClick={() => open('payables')}>Payment Run</button><button type="button" onClick={() => open('receivables')}>Customers</button><button type="button" onClick={() => open('comptroller')}>Comptroller</button><button type="button" onClick={() => open('reports')}>Reports</button><button type="button" onClick={() => open('setup')}>Setup</button></div></div></nav>; }
function Today() { return <section className="accounting-focus-grid accounting-balanced-grid"><Table title="Billing queue" rows={billingRows} empty="No billing items." /><Table title="Collections watch" rows={arRows} empty="No AR items." /><Table title="Vendor approval queue" rows={apRows} empty="No AP items." /><Table title="General ledger watch" rows={journalRows} empty="No ledger items." /></section>; }
function GeneralLedger() { return <section className="accounting-focus-grid accounting-balanced-grid"><Table title="General Ledger" rows={ledgerRows} empty="No ledger rows." /><Table title="AI General Ledger Builder" rows={aiLedgerRows} empty="No AI ledger recommendations." /><Table title="Journal entry queue" rows={journalRows} empty="No journal entries." /></section>; }
function Billing() { const [showCreate, setShowCreate] = useState(false); return <section className="accounting-focus-grid accounting-balanced-grid"><Card title="Customer billing queue" description="Progress billing, customer invoices, approvals, retainage, and send status." className="accounting-full-row accounting-expanded-payables"><div className="accounting-card-toolbar"><button type="button" onClick={() => setShowCreate((value) => !value)}>{showCreate ? 'Close invoice draft' : 'Create Invoice'}</button></div><div className="accounting-table">{billingRows.map((row, index) => <div className="accounting-table-row" key={`${row[0]}-${index}`}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b></div>)}</div></Card>{showCreate && <Card title="Create invoice" description="Create a full invoice draft." className="accounting-full-row accounting-wide-form"><div className="accounting-live-form accounting-wide-live-form"><label><span>Customer</span><input placeholder="Select customer" /></label><label><span>Project / Cost code</span><input placeholder="Project or cost code" /></label><label><span>Invoice amount</span><input placeholder="$0.00" /></label><label><span>Status</span><select defaultValue="draft"><option value="draft">Draft</option><option value="ready">Ready to send</option><option value="hold">Hold</option></select></label><label className="accounting-form-wide"><span>Notes</span><textarea rows="4" placeholder="Invoice notes" /></label><button type="button">Create draft invoice</button></div></Card>}</section>; }
function Insurance() { return <section className="accounting-focus-grid accounting-balanced-grid"><Table title="Insurance compliance" rows={insuranceRows} empty="No insurance items." /></section>; }
function PurchaseOrders() { const [showCreate, setShowCreate] = useState(false); return <section className="accounting-focus-grid accounting-balanced-grid"><Card title="Purchase order queue" description="Review vendor POs, approval status, receiving status, cost codes, and release controls." className="accounting-full-row accounting-expanded-payables"><div className="accounting-card-toolbar"><button type="button" onClick={() => setShowCreate((value) => !value)}>{showCreate ? 'Close purchase order draft' : 'Create Purchase Order'}</button></div><div className="accounting-table">{poRows.map((row, index) => <div className="accounting-table-row" key={`${row[0]}-${index}`}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b></div>)}</div></Card>{showCreate && <Card title="Create purchase order" description="Create a purchase order draft." className="accounting-full-row accounting-wide-form"><div className="accounting-live-form accounting-wide-live-form"><label><span>Vendor</span><input placeholder="Vendor name" /></label><label><span>Project / Cost code</span><input placeholder="Project or cost code" /></label><label><span>PO amount</span><input placeholder="$0.00" /></label><label className="accounting-form-wide"><span>Notes</span><textarea rows="4" placeholder="PO notes" /></label><button type="button">Create PO draft</button></div></Card>}</section>; }
function Receivables() { const [search, setSearch] = useState(''); const filteredRows = useMemo(() => { const clean = search.trim().toLowerCase(); return clean ? arRows.filter((row) => row.join(' ').toLowerCase().includes(clean)) : arRows; }, [search]); return <section className="accounting-focus-grid accounting-balanced-grid"><Card title="Accounts receivable filters" description="Search and filter customer balances." className="accounting-full-row accounting-filter-card"><div className="accounting-filter-grid"><label><span>Search customer</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Customer name, invoice, status" /></label></div></Card><Table title="Accounts receivable" rows={filteredRows} empty="No receivables match the filters." /></section>; }
function Payables() { return <section className="accounting-focus-grid accounting-balanced-grid"><Table title="Accounts payable" rows={apRows} empty="No payables." /></section>; }
function ScheduleOfValues() { return <section className="accounting-focus-grid accounting-balanced-grid"><Table title="Schedule of Values" rows={sovRows} empty="No SOV rows." /></section>; }
function ChangeOrders() { return <section className="accounting-focus-grid accounting-balanced-grid"><Table title="Change order queue" rows={changeOrderRows} empty="No change orders." /></section>; }
function Reports() { return <section className="accounting-report-room"><Table title="Accounting reports" rows={reportRows} empty="No reports." /></section>; }
function Comptroller({ open }) { const rows = [['Bank feed', 'Connect bank import before matching.', 'Needs setup'], ['AI matching', 'Suggests matches with confidence and reason codes.', 'Ready'], ['Review workflow', 'User reviews, edits, approves, or rejects each suggested match.', 'Available'], ['Posting controls', 'Approved matches can post internally or export to the accounting system.', 'Ready']]; return <section className="accounting-focus-grid accounting-balanced-grid"><Card title="Neroa Comptroller" description="AI accounting assistant for matching bank entries, bills, invoices, payments, cost codes, and project records." className="accounting-full-row accounting-expanded-payables"><div className="accounting-card-toolbar"><button type="button">Review unmatched entries</button><button type="button">Open match suggestions</button><button type="button" onClick={() => open('setup')}>Open setup</button></div><div className="accounting-table">{rows.map((row, index) => <div className="accounting-table-row" key={`${row[0]}-${index}`}><strong>{row[0]}</strong><span>{row[1]}</span><b>{row[2]}</b></div>)}</div></Card></section>; }
function NativeIntegrations() {
  const [integration, setIntegration] = useState(getInitialIntegrationState);
  const selectedProvider = providerById(integration.selected);
  const selectedState = providerState(integration, selectedProvider.id);
  function runProvider(id, action) {
    const provider = providerById(id);
    setIntegration((current) => {
      const next = { ...current, selected: id, providers: { ...current.providers } };
      const status = { ...defaultProviderState, ...(next.providers[id] || {}) };
      status.fireCount = (status.fireCount || 0) + 1;
      let message = '';
      if (action === 'setup') { status.status = 'Setup workspace open'; status.lastAction = 'Setup workspace opened'; message = `${provider.title} setup opened. Button fire #${status.fireCount}.`; }
      if (action === 'authorize') { status.authorized = true; status.connected = true; status.status = 'Authorized'; status.connectionRef = status.connectionRef || `conn-${provider.id}-${Date.now()}`; status.lastAction = 'Provider authorization saved'; message = `${provider.title} authorized. Button fire #${status.fireCount}.`; }
      if (action === 'test') { status.authorized = true; status.connected = true; status.connectionRef = status.connectionRef || `conn-${provider.id}-${Date.now()}`; status.test = 'Passed'; status.status = 'Connected'; status.lastAction = 'Connection test passed'; message = `${provider.title} connection test passed. Button fire #${status.fireCount}.`; }
      if (action === 'banks') { status.authorized = true; status.connected = true; status.connectionRef = status.connectionRef || `conn-${provider.id}-${Date.now()}`; status.banks = bankAccounts[id] || []; status.status = 'Bank accounts ready'; status.lastAction = 'Bank import preview loaded'; message = `${provider.title}: ${status.banks.length} bank accounts loaded. Button fire #${status.fireCount}.`; }
      if (action === 'preview') { status.migration = migrationAreas.map((row) => row.slice()); status.status = 'Migration preview ready'; status.lastAction = 'Migration preview built'; message = `${provider.title} migration preview built. Button fire #${status.fireCount}.`; }
      if (action === 'approve') { if (!status.migration.length) status.migration = migrationAreas.map((row) => row.slice()); status.approved = status.migration.map((_, index) => index); status.status = 'Migration approved'; status.lastAction = 'Migration preview approved'; message = `${provider.title} migration preview approved. Button fire #${status.fireCount}.`; }
      next.providers[id] = status;
      next.message = message;
      next.activity = [`${new Date().toLocaleTimeString()} - ${message}`, ...(next.activity || [])].slice(0, 8);
      saveIntegrationState(next);
      writeProviderContext(provider, status, action);
      return next;
    });
  }
  return <section className="accounting-focus-grid accounting-balanced-grid"><Card title="Accounting integrations and migrations" description="These buttons fire on pointer-down so the action happens as soon as the button is pressed." className="accounting-full-row accounting-expanded-payables"><div className="accounting-card-toolbar">{providers.map((provider) => <FireButton key={provider.id} action={() => runProvider(provider.id, 'setup')}>{provider.title}</FireButton>)}</div>{integration.message && <div className="accounting-empty"><strong>Last action:</strong> {integration.message}</div>}<div className="accounting-table">{providers.map((provider) => { const status = providerState(integration, provider.id); return <div className="accounting-table-row" key={provider.id}><strong>{provider.title}</strong><span>{provider.kind}. {status.lastAction}</span><b>{status.status}</b></div>; })}</div></Card><Card title={`${selectedProvider.title} setup workspace`} description="Press a button once. The output tables below update immediately." className="accounting-full-row accounting-expanded-payables"><div className="accounting-card-toolbar"><FireButton action={() => runProvider(selectedProvider.id, 'authorize')}>Authorize Provider</FireButton><FireButton action={() => runProvider(selectedProvider.id, 'test')}>Test Connection</FireButton><FireButton action={() => runProvider(selectedProvider.id, 'banks')}>Pull Bank Accounts</FireButton><FireButton action={() => runProvider(selectedProvider.id, 'preview')}>Migration Preview</FireButton><FireButton action={() => runProvider(selectedProvider.id, 'approve')}>Approve Preview</FireButton></div><div className="accounting-table"><div className="accounting-table-row"><strong>Status</strong><span>{selectedState.lastAction}</span><b>{selectedState.status}</b></div><div className="accounting-table-row"><strong>Connection ref</strong><span>{selectedState.connectionRef || 'Press a button to create a connection reference'}</span><b>{selectedState.test}</b></div><div className="accounting-table-row"><strong>Button fires</strong><span>{selectedState.fireCount || 0} total actions for this provider</span><b>Live</b></div></div></Card><Table title="Bank account import preview" rows={(selectedState.banks.length ? selectedState.banks : [['No bank accounts loaded', 'Press Pull Bank Accounts.', 'Waiting']])} empty="No bank accounts." /><Table title="Migration approval preview" rows={(selectedState.migration.length ? selectedState.migration.map((row, index) => [row[0], row[1], selectedState.approved.includes(index) ? 'Approved' : row[2]]) : [['No migration preview', 'Press Migration Preview.', 'Waiting']])} empty="No migration rows." />{integration.activity?.length ? <Table title="Integration activity" rows={integration.activity.map((entry) => [entry, selectedProvider.title, 'Logged'])} empty="No activity." /> : null}</section>;
}
function Setup() { const rows = [['Connect accounting provider', 'Use the native integration cards above for QuickBooks/Foundation setup.', 'Required'], ['Pull bank accounts', 'Import read-only bank account previews for review.', 'Required'], ['Build migration preview', 'Map accounts, customers, vendors, invoices, bills, banks, and cost codes.', 'Required'], ['Approve before posting', 'Final posting stays locked until user approval.', 'Required']]; return <><NativeIntegrations /><section className="accounting-focus-grid accounting-balanced-grid"><Table title="Accounting setup checklist" rows={rows} empty="No setup tasks." /></section></>; }
export default function AccountingPortal() {
  const [active, setActive] = useState(pathSection);
  function open(section) { const safe = validSections.has(section) ? section : 'today'; history.pushState({}, '', url(safe)); setActive(safe); window.dispatchEvent(new PopStateEvent('popstate')); }
  let body = null;
  if (active === 'today') body = <Today />; else if (active === 'ledger') body = <GeneralLedger />; else if (active === 'billing') body = <Billing />; else if (active === 'insurance') body = <Insurance />; else if (active === 'purchase-orders') body = <PurchaseOrders />; else if (active === 'receivables') body = <Receivables />; else if (active === 'payables') body = <Payables />; else if (active === 'sov') body = <ScheduleOfValues />; else if (active === 'change-orders') body = <ChangeOrders />; else if (active === 'reports') body = <Reports />; else if (active === 'comptroller') body = <Comptroller open={open} />; else body = <Setup />;
  return <><Nav active={active} open={open} />{body}</>;
}
